# Generated by Django 5.1 on 2024-08-22 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='debtors',
        ),
        migrations.AddField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='debts.debtor'),
        ),
    ]
